# Site settings
title: Nerves
email: core@nerves.io
description: > # this means to ignore newlines until "baseurl:"
  Cross-compiled Erlang for Embedded Devices
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nerves.io" # the base hostname & protocol for your site
twitter_username: NervesProject
github_username:  Nerves-Project

# Build settings
markdown: kramdown
